version: '3.7'

services:

  web:
    image: mtiganik/teacher-back-image
    container_name: teacher-app
    ports:
      - "5000:80"
    depends_on:
      - db
  
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=${DB_SA_PASSWORD}
      - ACCEPT_EULA=Y

# Connection string if used with docker
# "sqlConnection": "Server=host.docker.internal;Database=teacher-back;User ID=sa;Password=A!VeryComplex123Password;MultipleActiveResultSets=true;"
