version: '3.7'

services:

  web:
    image: mtiganik/teacher-back-image
    container_name: teacher-app
    ports:
      - "5000:80"
    # build: .
    # depends_on:
    #   - db
    # environment:
    #     - db__connectionString=Server=localhost\\MSSQLSERVER01;Database=teacher-back;Integrated Security=True;User ID=${DB_SA_USER};Password=${DB_SA_PASSWORD};
  
  # db:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   container_name: mssql
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     - SA_PASSWORD=${DB_SA_PASSWORD}
  #     - ACCEPT_EULA=Y