// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using teacher.Db.Data;

#nullable disable

namespace teacher.Db.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230123234433_defaultValues")]
    partial class defaultValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("teacher.Models.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PostId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighestDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceMax")
                        .HasColumnType("int");

                    b.Property<int>("PriceMin")
                        .HasColumnType("int");

                    b.Property<string>("Speciality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1989, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Õpetan matemaatikat, Füüsikat, programmeerimist keskkooli, ülikooli tasemel",
                            Email = "mtiganik@gmail.com",
                            FirstName = "Mihkel",
                            HighestDegree = "Ülikool",
                            Languages = "Eesti, Inglise, Vene",
                            LastName = "Tiganik",
                            Location = "Tallinn, Harjumaa",
                            Phone = "55655828",
                            PicturePath = "https://scontent-hel3-1.xx.fbcdn.net/v/t39.30808-6/246660293_10216443541721640_696967518917121996_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=dLGcrq3NYUUAX8ZejJ6&_nc_ht=scontent-hel3-1.xx&oh=00_AfBVRoRLRJF0b3vz2J4XKZ52_WHH7DQLmv-ShjxvRIpxwg&oe=63D174B9",
                            PriceMax = 50,
                            PriceMin = 30,
                            Speciality = "Insener, Õpetaja"
                        });
                });

            modelBuilder.Entity("teacher.Models.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Basic")
                        .HasColumnType("bit");

                    b.Property<bool>("Elementary")
                        .HasColumnType("bit");

                    b.Property<bool>("High")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<bool>("University")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Basic = true,
                            Elementary = false,
                            High = true,
                            Name = "Matemaatika",
                            PostId = 1,
                            University = true
                        },
                        new
                        {
                            Id = 2,
                            Basic = true,
                            Elementary = true,
                            High = true,
                            Name = "Füüsika",
                            PostId = 1,
                            University = true
                        },
                        new
                        {
                            Id = 3,
                            Basic = true,
                            Elementary = true,
                            High = true,
                            Name = "Programmeerimine",
                            PostId = 1,
                            University = true
                        });
                });

            modelBuilder.Entity("teacher.Models.Models.TeachingTakesPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherLocation")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<bool>("StudentsPlace")
                        .HasColumnType("bit");

                    b.Property<bool>("TeachersPlace")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("TeachingTakesPlace");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Online = true,
                            OtherLocation = false,
                            PostId = 1,
                            StudentsPlace = true,
                            TeachersPlace = true
                        });
                });

            modelBuilder.Entity("teacher.Models.Models.Subject", b =>
                {
                    b.HasOne("teacher.Models.Models.Post", null)
                        .WithMany("TeachSubjects")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("teacher.Models.Models.TeachingTakesPlace", b =>
                {
                    b.HasOne("teacher.Models.Models.Post", null)
                        .WithOne("TeachingTakesPlace")
                        .HasForeignKey("teacher.Models.Models.TeachingTakesPlace", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("teacher.Models.Models.Post", b =>
                {
                    b.Navigation("TeachSubjects");

                    b.Navigation("TeachingTakesPlace");
                });
#pragma warning restore 612, 618
        }
    }
}
