# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - opetajateApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://opetajatekonteinerregisterback.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b753c4cf5e0b41b080000f3672ee6d58 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a58d1b3bb4c943619d71a4b8b1e74bca }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: opetajatekonteinerregisterback.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b753c4cf5e0b41b080000f3672ee6d58 }}/teacher-back:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'opetajateApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_20e169485e9145dfb029fc6963107972 }}
        images: 'opetajatekonteinerregisterback.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b753c4cf5e0b41b080000f3672ee6d58 }}/teacher-back:${{ github.sha }}'